[package]
name = "huginn-proxy"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
huginn-proxy-lib = { path = "../huginn-proxy-lib" }
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
tokio = { version = "1.48.0", features = ["macros", "rt-multi-thread", "signal"] }
tracing.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true
