[package]
name = "huginn-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true

[[bin]]
name = "huginn-proxy"
path = "src/main.rs"

[dependencies]
huginn-proxy-lib = { path = "../huginn-proxy-lib", version = "0.1.0" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

