[workspace]
members = [
    "examples",
    "huginn-proxy",
    "huginn-proxy-bench",
    "huginn-proxy-lib",
    "huginn-proxy-tls",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
repository = "https://github.com/biandratti/huginn-proxy"
homepage = "https://github.com/biandratti/huginn-proxy"

[workspace.metadata.publish]
exclude = ["huginn-proxy-bench", "examples"]

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
