[workspace]
members = ["huginn-proxy", "huginn-proxy-lib"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
repository = "https://github.com/biandratti/huginn-proxy"
homepage = "https://github.com/biandratti/huginn-proxy"

[workspace.dependencies]
ahash = "0.8.12"
dashmap = "7.0.0-rc2"
rand = "0.9.2"
rcgen = "0.14.6"
rustls = "0.23.35"
rustls-pki-types = "1.13.2"
serde = { version = "1.0.228", features = ["derive"] }
tempfile = "3.23.0"
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["net", "time", "io-util", "macros", "rt-multi-thread", "sync", "signal"] }
tokio-rustls = "0.26.4"
toml = "0.9.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }
huginn-net-tls = "1.7.0"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
