[workspace]
members = ["huginn-proxy", "huginn-proxy-lib"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
repository = "https://github.com/biandratti/huginn-proxy"
homepage = "https://github.com/biandratti/huginn-proxy"

[workspace.dependencies]
ahash = "0.8.12"
anyhow = "1.0.100"
async-trait = "0.1.89"
bytes = "1.11.0"
clap = { version = "4.5.51", features = ["derive"] }
criterion = "0.8.1"
ctrlc = "3.5.1"
serde_json = "1.0.145"
tracing-appender = "0.2.4"
futures-util = "0.3.31"
http = "1.4.0"
http-body-util = "0.1.3"
h2 = "0.4.12"
hyper = { version = "1.8.1", features = ["full"] }
hyper-util = { version = "0.1.19", features = ["full"] }
rand = "0.9.2"
rustls = "0.23.35"
rustls-pemfile = "2.1.3"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["net", "time", "io-util", "macros", "rt-multi-thread", "sync", "signal"] }
tokio-rustls = "0.26.4"
tokio-util = "0.7.17"
toml = "0.9.8"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["fmt", "env-filter"] }
crossbeam-channel = "0.5.15"
hpack-patched = "0.3.0"
huginn-net-db = { path = "data/huginn-net/huginn-net-db" }
huginn-net-http = { path = "data/huginn-net/huginn-net-http" }
lazy_static = "1.5.0"
nom = "8.0.0"
pcap-file = "3.0.0-rc1"
pnet = "0.35.0"
sha2 = "0.10.9"
tls-parser = "0.12.2"
ttl_cache = "0.5.1"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
