[workspace]
members = [
    "examples",
    "huginn-proxy",
    "huginn-proxy-bench",
    "huginn-proxy-lib",
    "huginn-proxy-tls",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
license = "MIT OR Apache-2.0"
authors = ["Maximiliano Biandratti"]
repository = "https://github.com/biandratti/huginn-proxy"
homepage = "https://github.com/biandratti/huginn-proxy"

[workspace.metadata.publish]
exclude = ["huginn-proxy-bench", "examples"]

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true

[workspace.dependencies]
clap = { version = "4.5.53", features = ["derive"] }
tokio = { version = "1.48.0", features = ["net", "io-util", "rt", "time", "macros", "rt-multi-thread"] }
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["env-filter", "fmt"] }
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
thiserror = "2.0.17"
