[advisories]
version = 2
unmaintained = "all"
# Exception for paste: transitive dependency of thirtyfour (used in tests-browsers)
# See: https://rustsec.org/advisories/RUSTSEC-2024-0436
ignore = [
    "RUSTSEC-2024-0436",
]

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Unicode-3.0",
    "ISC",
    "BSD-3-Clause",
    "OpenSSL",
    "CC0-1.0",
    "CDLA-Permissive-2.0",
    "Zlib",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "allow"
wildcards = "deny"
# TODO: Temporal...
allow-wildcard-paths = true

[sources]
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
