[package]
name = "huginn-proxy-ebpf"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
aya.workspace = true
thiserror.workspace = true
tracing.workspace = true

[build-dependencies]
