[package]
name = "huginn-proxy-lib"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish = true

[lib]
name = "huginn_proxy_lib"
path = "src/lib.rs"

[dependencies]
ahash.workspace = true
dashmap.workspace = true
huginn-net-tls.workspace = true
rand.workspace = true
rustls.workspace = true
rustls-pki-types.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
toml.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
rcgen.workspace = true
tempfile.workspace = true


