[package]
name = "huginn-proxy-lib"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish = true

[lib]
name = "huginn_proxy_lib"
path = "src/lib.rs"

[dependencies]
ahash.workspace = true
rand.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true
toml.workspace = true
tracing.workspace = true


